baseURL = "http://ccviolett.github.io"
title = "罗潇阳的博客"
theme = "hugo-coder"
languageCode = "zh-cn"
defaultContentLanguage = "zh-cn"
paginate = 20
pygmentsStyle = "b2"
pygmentsCodeFences = true
pygmentsCodeFencesGuessSyntax = true
enableEmoji = true
# Enable Disqus comments
# disqusShortname = "yourdiscussshortname"
enableInlineShortcodes = true

[params]
author = "罗潇阳"
description = "罗潇阳的个人网站"
keywords = "博客,开发者,个人"
info = ["全栈开发学习人员", "魔术师"]
avatarURL = "images/avatar.jpg"
#gravatar = "john.doe@example.com"
footerContent = "愿你成为自己的太阳，无需借助别人的光。</br>博客接受大众投稿，联系QQ 3340751717。"
dateFormat = "2006 年 1 月 2 日"
hideFooter = false
hideCredits = false
hideCopyright = false
since = 2022
# Git Commit in Footer, uncomment the line below to enable it
commit = "https://github.com/luizdepra/hugo-coder/tree/"
# Right To Left, shift content direction for languagues such as Arabic
rtl = false
# Specify light/dark colorscheme
# Supported values:
# "auto" (use preference set by browser)
# "dark" (dark background, light foreground)
# "light" (light background, dark foreground) (default)
colorScheme = "auto"
# Hide the toggle button, along with the associated vertical divider
hideColorSchemeToggle = false
# Series see also post count
maxSeeAlsoItems = 5
# Custom CSS
customCSS = []
# Custom SCSS, file path is relative to Hugo's asset folder (default: {your project root}/assets)
customSCSS = []
# Custom JS
customJS = []

# If you want to use fathom(https://usefathom.com) for analytics, add this section
# [params.fathomAnalytics]
# siteID = "ABCDE"
# serverURL = "analytics.example.com" # Default value is cdn.usefathom.com, overwrite this if you are self-hosting

# If you want to use plausible(https://plausible.io) for analytics, add this section
# [params.plausibleAnalytics]
# domain = "example.com"
# serverURL = "analytics.example.com" # Default value is plausible.io, overwrite this if you are self-hosting or using a custom domain

# If you want to use goatcounter(https://goatcounter.com) for analytics, add this section
# [params.goatCounter]
# code = "code"

# If you want to use Cloudflare Web Analytics(https://cloudflare.com) for analytics, add this section
# [params.cloudflare]
# token = "token"

# If you want to use Matomo(https://matomo.org) for analytics, add this section
# [params.matomo]
# siteID = "ABCDE" # Default value is "1", overwrite this if you are cloud-hosting
# serverURL = "analytics.example.com" # For cloud-hosting, use provided URL, e.g. example.matomo.cloud

# If you want to use Google Tag Manager(https://analytics.google.com/) for analytics, add this section
# [params.googleTagManager]
# id = "gid"

# If you want to implement a Content-Security-Policy, add this section
# [params.csp]
# childsrc = ["'self'"]
# fontsrc = ["'self'", "https://fonts.gstatic.com", "https://cdn.jsdelivr.net/"]
# formaction = ["'self'"]
# framesrc = ["'self'"]
# imgsrc = [
#   "'self'",
#   "https://*.aliyuncs.com",
# 	"https://hm.baidu.com",
#   "https://*.loli.net",
#   "https://ccviolett-1307804825.cos.ap-shanghai.myqcloud.com/img/"
# ]
# objectsrc = ["'none'"]
# stylesrc = [
#   "'self'",
#   "'unsafe-inline'",
#   "https://fonts.googleapis.com/",
#   "https://cdn.jsdelivr.net/"
# ]
# scriptsrc = [
#   "'self'", 
#   "'unsafe-inline'", 
#   "https://www.google-analytics.com",
# 	"https://hm.baidu.com"
#   "https://cdn.jsdelivr.net/"
# ]
# prefetchsrc = ["'self'"]
# connect-src directive – defines valid targets for to XMLHttpRequest (AJAX), WebSockets or EventSource
# connectsrc = ["'self'", "https://www.google-analytics.com"]

[taxonomies]
category = "categories"
series = "series"
tag = "tags"
author = "authors"

[[params.social]]
name = "Github"
icon = "fa fa-github"
weight = 1
url = "https://github.com/ccviolett/"

[[params.social]]
name = "Gitlab"
icon = "fa fa-gitlab"
weight = 2
url = "https://gitlab.com/ccviolett/"

[[params.social]]
name = "LinkedIn"
icon = "fa fa-linkedin"
weight = 3
url = "https://www.linkedin.com/in/ccviolett/"

[[params.social]]
name = "RSS"
icon = "fa fa-rss"
weight = 4
url = "https://ccviolett.github.io/index.xml"
rel = "alternate"
type = "application/rss+xml"

[languages.zh-cn]
languageName = ":cn:"

[[languages.zh-cn.menu.main]]
name = "首页"
weight = 1
url = "/"

[[languages.zh-cn.menu.main]]
name = "文章"
weight = 2
url = "posts/"

[[languages.zh-cn.menu.main]]
name = "题解"
weight = 3
url = "solution/"

[[languages.zh-cn.menu.main]]
name = "联系"
weight = 5
url = "contact/"

[[languages.zh-cn.menu.main]]
name = "关于"
weight = 6
url = "about/"

[[languages.zh-cn.menu.main]]
name = "赞助"
weight = 7
url = "support/"

# For English

[languages.en]
languageName = ":uk:"
title = "CC Violett's Blog"

[languages.en.params]
author = "Carmine Carlo"
info = ["Full Stack DevOps", "Magician"]
description = "Carmine Carlo's personal website"
keywords = "blog,developer,personal"
footerContent = "Welcome to my blog."
dateFormat = "January 2, 2006"

[[languages.en.menu.main]]
name = "Home"
weight = 1
url = "/"

[[languages.en.menu.main]]
name = "Blog"
weight = 2
url = "posts/"

[[languages.en.menu.main]]
name = "Solution"
weight = 3
url = "solution/"

[[languages.en.menu.main]]
name = "Contact"
weight = 5
url = "contact/"

[[languages.en.menu.main]]
name = "About"
weight = 6
url = "about/"

# Enable html support inside markdown
[markup]
  [markup.goldmark]
    [markup.goldmark.renderer]
      unsafe = true
  [markup.highlight]
    anchorLineNos = false
    codeFences = true
    guessSyntax = false
    hl_Lines = ''
    lineAnchors = ''
    lineNoStart = 1
    lineNos = false
    lineNumbersInTable = true
    noClasses = true
    noHl = false
    style = 'algol'
    tabWidth = 4